// <auto-generated />
using System;
using MVCLibraryApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCLibraryApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCLibraryApp.Models.AbonnementModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Abonnementskosten")
                        .HasColumnType("float");

                    b.Property<double>("Boetekosten")
                        .HasColumnType("float");

                    b.Property<int>("MaximaleItems")
                        .HasColumnType("int");

                    b.Property<double>("Reserveringskosten")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uitleentermijn")
                        .HasColumnType("int");

                    b.Property<int>("Verlengingen")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Abonnementen");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.BezoekerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AbonnementID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lidmaatschapsstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AbonnementID");

                    b.ToTable("Bezoekers");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.ItemModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocatieID")
                        .HasColumnType("int");

                    b.Property<int>("Publicatiejaar")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LocatieID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.LeningModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BezoekerID")
                        .HasColumnType("int");

                    b.Property<double>("Boetekosten")
                        .HasColumnType("float");

                    b.Property<DateTime>("Einddatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("MedewerkerModelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BezoekerID");

                    b.HasIndex("ItemID");

                    b.HasIndex("MedewerkerModelID");

                    b.ToTable("Lenings");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.LocatieModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Locaties");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.MedewerkerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.ReserveringModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BezoekerID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int?>("MedewerkerModelID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BezoekerID");

                    b.HasIndex("ItemID");

                    b.HasIndex("MedewerkerModelID");

                    b.ToTable("Reserveringen");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.BezoekerModel", b =>
                {
                    b.HasOne("MVCLibraryApp.Models.AbonnementModel", "Abonnement")
                        .WithMany("Bezoekers")
                        .HasForeignKey("AbonnementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonnement");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.ItemModel", b =>
                {
                    b.HasOne("MVCLibraryApp.Models.LocatieModel", "Locatie")
                        .WithMany("Items")
                        .HasForeignKey("LocatieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locatie");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.LeningModel", b =>
                {
                    b.HasOne("MVCLibraryApp.Models.BezoekerModel", "Bezoeker")
                        .WithMany("Lenings")
                        .HasForeignKey("BezoekerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCLibraryApp.Models.ItemModel", "Item")
                        .WithMany("Lenings")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCLibraryApp.Models.MedewerkerModel", null)
                        .WithMany("Lenings")
                        .HasForeignKey("MedewerkerModelID");

                    b.Navigation("Bezoeker");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.ReserveringModel", b =>
                {
                    b.HasOne("MVCLibraryApp.Models.BezoekerModel", "Bezoeker")
                        .WithMany("Reserverings")
                        .HasForeignKey("BezoekerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCLibraryApp.Models.ItemModel", "Item")
                        .WithMany("Reserverings")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCLibraryApp.Models.MedewerkerModel", null)
                        .WithMany("Reserverings")
                        .HasForeignKey("MedewerkerModelID");

                    b.Navigation("Bezoeker");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.AbonnementModel", b =>
                {
                    b.Navigation("Bezoekers");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.BezoekerModel", b =>
                {
                    b.Navigation("Lenings");

                    b.Navigation("Reserverings");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.ItemModel", b =>
                {
                    b.Navigation("Lenings");

                    b.Navigation("Reserverings");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.LocatieModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MVCLibraryApp.Models.MedewerkerModel", b =>
                {
                    b.Navigation("Lenings");

                    b.Navigation("Reserverings");
                });
#pragma warning restore 612, 618
        }
    }
}
